version: '3.8'

services:
  duckduckfind:
    build: .
    ports:
      - "5556:5556"
    environment:
      FLASK_ENV: development
    volumes:
      - ./documents:/app/Documents
    user: "1000:1000"  # Ensure container runs with a specific user to avoid permission issues
