version: '3.8'

services:
  duckduckfind:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5111:5111"
    volumes:
      - ./documents:/app/documents
    environment:
      - FLASK_ENV=production
    command: sh -c "python app.py"

