services:
  duckduckfind:
    build: .
    ports:
      - "5556:5556"
    environment:
      FLASK_ENV: development
    volumes:
      - ./documents:/app/Documents
    user: "1000:1000"  # Might be needed for writing settings.json
    restart: "always"
