# This file is auto-generated by the application.

settings_output = {
    "ENABLE_LOGGING": {
        "title": 'Enable Logging',
        "value": True,
        "description": 'Enables detailed logging of all requests and responses.'
    },
    "language_to_output_format": {
        "title": 'Language to Output',
        "value": "{'swedish_kr': 'Priset på en {symbol} aktie är: {price:.2f} kr', 'swedish_dollar': 'Priset på en {symbol} aktie är: {price:.2f} dollar', 'english': 'The current price of a {symbol} stock is ${price:.2f}.', 'german': 'Der aktuelle Preis einer {symbol} Aktie beträgt {price:.2f} €.', 'french': 'Le prix actuel d\\'une action {symbol} est de {price:.2f} €.', 'spanish': 'El precio actual de una acción de {symbol} es {price:.2f} €.', 'italian': 'Il prezzo attuale di un\\'azione {symbol} è {price:.2f} €.', 'norwegian': 'Prisen på en {symbol} aksje er {price:.2f} kr.', 'dutch': 'De huidige prijs van een {symbol} aandeel is {price:.2f} €.'}",
        "description": 'Formats the stock price response based on the language.'
    },
}
