# This file is auto-generated by the application.

settings_general = {
    "DEFAULT_LANGUAGE": {
        "title": 'Default Language',
        "value": 'english',
        "description": 'The default language to use when language detection fails.'
    },
    "ENABLE_TRANSPORT": {
        "title": 'Enable Transport',
        "value": False,
        "description": 'Enables the option to search for public transportation. (Sweden only)'
    },
    "ENABLE_DOCUMENT": {
        "title": 'Enable Document',
        "value": False,
        "description": 'Enables the option to search your local documents.'
    },
    "ENABLE_STOCK": {
        "title": 'Enable Stock Market',
        "value": True,
        "description": 'Enables the option to search the stock market.'
    },
    "ENABLE_PHOTO": {
        "title": 'Enable Photo',
        "value": True,
        "description": 'Enables the option to search your local photos.'
    },
    "transport_triggers": {
        "title": 'Transport Triggers',
        "value": "['buss', 'bussen', 'tåg', 'tåget', 'flyg', 'flyget', 'spårvagn', 'spårvagnen']",
        "description": 'List of keywords to trigger public transportation-related searches. (Sweden only)'
    },
    "document_triggers": {
        "title": 'Document Triggers',
        "value": "['doc', 'document', 'pdf']",
        "description": 'List of keywords to trigger searching local documents.'
    },
    "stock_triggers": {
        "title": 'Stock Triggers',
        "value": "['aktie', 'price', 'quote']",
        "description": 'List of keywords to trigger stock-related searches.'
    },
    "photos_triggers": {
        "title": 'Photos Triggers',
        "value": "['photo', 'photos', 'images']",
        "description": 'List of keywords to trigger searching local photos.'
    },
    "stock_name_to_symbol": {
        "title": 'Stock name to symbol',
        "value": "{'apple': 'AAPL', 'nvidia': 'NVDA', 'electrolux': 'ELUX-B.ST', 'nordea': 'NDA-SE.ST', 'volvo': 'VOLV-B.ST', 'volkswagen': 'VOW3.DE', 'equinor': 'EQNR.OL', 'asml': 'ASML.AS'}",
        "description": 'Maps stock names to their respective symbols. If DuckDuckFind is having trouble finding a specific stock, you can manually set its yfinance stock symbol here.'
    },
    "language_to_country_code": {
        "title": 'Language to Country Code',
        "value": "{'swedish': '.ST', 'english': '', 'german': '.DE', 'french': '.PA', 'spanish': '.MC', 'italian': '.MI', 'norwegian': '.OL', 'dutch': '.AS'}",
        "description": 'Maps language to its respective country code for stock markets queries.'
    },
}
