# This file is auto-generated by the application.

settings_viewer = {
    "ENABLE_VIEWER": {
        "title": 'Enable Viewer',
        "value": True,
        "description": 'Enables the Viewer to display photos based on search queries, such as displaying photos from specific years or time periods. By default, it shows Photo Memories from exactly one year ago.'
    },
}
