# This file is auto-generated by the application.

settings_scrape = {
    "ENABLE_EPG": {
        "value": False,
        "description": 'Enables you to create your own customized EPG (Electronic Program Guide), by specifying a URL to scrape for data, for each of your channels. After scraping, the data is analyzed, processed and extracted into JSON, after which all your channel data is combined into a proper xmltv format to be used as a EPG. This service also comes with a built in web application at http://localhost:5556/epg'
    },
}
