# This file is auto-generated by the application.

settings_search = {
    "SEARCH_DEPTH": {
        "title": 'Search Depth',
        "value": 60,
        "description": 'Determines how many websites will be searched.'
    },
    "FALLBACK_TO_AI_CHAT": {
        "title": 'Fallback to AI Chat',
        "value": True,
        "description": 'If enabled, the system will fallback to an AI chat mode if the search fails.'
    },
    "LOOP_UNTIL_SUCCESS": {
        "title": 'Loop Until Success',
        "value": False,
        "description": 'If true, the system will continue to attempt the search until it succeeds.'
    },
    "REGION": {
        "title": 'Region',
        "value": 'se-sv',
        "description": 'Regional Web Searches.'
    },
    "DOCS_CONTEXT_LINES": {
        "title": 'Docs Context Lines',
        "value": 4,
        "description": 'The number of lines before and after the matched line when searching your local documents.'
    },
}
