# This file is auto-generated by the application.

settings_connect = {
    "TRAFIKLAB_API_TOKEN": {
        "title": 'TrafikLab API Token',
        "value": '',
        "description": 'Required for public transportation queries. Create a ReseRobot project and generate your FREE token at https://www.trafiklab.se/docs/using-trafiklab/getting-started/'
    },
}
