# This file is auto-generated by the application.

settings_score = {
    "MIN_SCORE_THRESHOLD": {
        "title": 'Minimum Score Threshold',
        "value": 6,
        "description": 'Minimum score threshold for search results to be considered relevant.'
    },
    "important_phrases": {
        "title": 'Important Phrases',
        "value": "['stänger', 'öppnar', 'öppettider', 'umeå', 'när', 'tid', 'datum', 'match', 'klockan', 'pris', 'väder', 'regn', 'idag', 'imorgon', 'björklöven', 'björklövens']",
        "description": 'A list of words giving double score (+2).'
    },
}
